import jsPDF from "jspdf";

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 6;

function addPageIfNeeded(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > 280) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

export type CommitStoryPdfInput = {
  repoName: string;
  summaryParagraph: string;
  features: string[];
  fixes: string[];
  improvements: string[];
  portfolioBullets: string[];
};

export function generateCommitStoryPdf(input: CommitStoryPdfInput) {
  const { repoName, summaryParagraph, features, fixes, improvements, portfolioBullets } = input;

  const doc = new jsPDF();
  let y = MARGIN;

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("Commit Story Report", MARGIN, y);
  y += 10;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(repoName, MARGIN, y);
  y += 4;
  doc.text(`Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`, MARGIN, y);
  doc.setTextColor(0);
  y += 10;

  doc.setDrawColor(200);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("AI Summary", MARGIN, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryLines = doc.splitTextToSize(summaryParagraph || "No summary available.", CONTENT_WIDTH);
  doc.text(summaryLines, MARGIN, y);
  y += summaryLines.length * LINE_HEIGHT + 8;

  // jsPDF built-in fonts (Helvetica) do not support emoji — they corrupt following text.
  const sections: { title: string; items: string[] }[] = [
    { title: "Features", items: features.length ? features : ["(None in sample)"] },
    { title: "Bug Fixes", items: fixes.length ? fixes : ["(None in sample)"] },
    { title: "Improvements", items: improvements.length ? improvements : ["(None in sample)"] },
  ];

  for (const section of sections) {
    y = addPageIfNeeded(doc, y, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(section.title, MARGIN, y);
    y += 7;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    for (const item of section.items) {
      y = addPageIfNeeded(doc, y, 8);
      doc.text(`•  ${item}`, MARGIN + 4, y);
      y += LINE_HEIGHT;
    }
    y += 6;
  }

  y = addPageIfNeeded(doc, y, 40);
  doc.setDrawColor(200);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Portfolio Highlights", MARGIN, y);
  y += 8;

  const portfolio = portfolioBullets.length ? portfolioBullets : ["_Generate highlights from a repository with commit history._"];

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  for (const item of portfolio) {
    y = addPageIfNeeded(doc, y, 14);
    const lines = doc.splitTextToSize(`•  ${item}`, CONTENT_WIDTH - 4);
    doc.text(lines, MARGIN + 4, y);
    y += lines.length * LINE_HEIGHT + 2;
  }

  y += 6;
  y = addPageIfNeeded(doc, y, 10);
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by GitScribe", MARGIN, y);

  const slug = repoName.replace(/\//g, "-").replace(/[^a-zA-Z0-9-]/g, "") || "report";
  doc.save(`gitscribe-${slug}.pdf`);
}
